#!/usr/bin/env bash
# First-time setup — creates .env + odoo configs with strong random passwords.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# 48-char hex (192-bit) — safe in .env and odoo.conf without quoting issues
gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  else
    python3 -c "import secrets; print(secrets.token_hex(24))"
  fi
}

sed_inplace() {
  local expr="$1"
  local file="$2"
  if sed --version >/dev/null 2>&1; then
    sed -i "$expr" "$file"
  else
    sed -i '' "$expr" "$file"
  fi
}

SECRETS_FILE="${ROOT}/.setup-secrets"
ODOO_DB_NAME="mycompany"
[[ -f .env ]] && set -a && source .env && set +a
ODOO_DB_NAME="${ODOO_DB_NAME:-mycompany}"

CREATED=()
SECRETS_BODY=""

write_env() {
  local db_pass="$1"
  local db_name="$2"
  cat > .env <<EOF
# Generated by scripts/setup.sh — keep private (chmod 600)
POSTGRES_USER=odoo
POSTGRES_PASSWORD=${db_pass}
POSTGRES_DB=postgres

HOST=db
USER=odoo
PASSWORD=${db_pass}

ODOO_DB_NAME=${db_name}
EOF
  chmod 600 .env
}

write_odoo_conf() {
  local dest="$1"
  local example="$2"
  local master_pass="$3"
  local db_name="$4"
  cp "$example" "$dest"
  sed_inplace "s/^admin_passwd = .*/admin_passwd = ${master_pass}/" "$dest"
  sed_inplace "s/^dbfilter = .*/dbfilter = ^${db_name}\$/" "$dest"
  chmod 600 "$dest"
}

write_odoo_dev_conf() {
  local dest="$1"
  local example="$2"
  local master_pass="$3"
  cp "$example" "$dest"
  sed_inplace "s/^admin_passwd = .*/admin_passwd = ${master_pass}/" "$dest"
  chmod 600 "$dest"
}

if [[ ! -f .env ]]; then
  DB_PASS="$(gen_secret)"
  write_env "$DB_PASS" "$ODOO_DB_NAME"
  CREATED+=(".env")
  SECRETS_BODY+="Postgres + Odoo DB password (POSTGRES_PASSWORD / PASSWORD):
  ${DB_PASS}

"
  echo "Created .env"
fi

if [[ ! -f config/odoo.conf ]]; then
  PROD_MASTER="$(gen_secret)"
  write_odoo_conf config/odoo.conf config/odoo.conf.example "$PROD_MASTER" "$ODOO_DB_NAME"
  CREATED+=("config/odoo.conf")
  SECRETS_BODY+="Odoo master password — production (admin_passwd in odoo.conf):
  ${PROD_MASTER}

"
  echo "Created config/odoo.conf"
fi

if [[ ! -f config/odoo.dev.conf ]]; then
  DEV_MASTER="$(gen_secret)"
  write_odoo_dev_conf config/odoo.dev.conf config/odoo.dev.conf.example "$DEV_MASTER"
  CREATED+=("config/odoo.dev.conf")
  SECRETS_BODY+="Odoo master password — development (admin_passwd in odoo.dev.conf):
  ${DEV_MASTER}

"
  echo "Created config/odoo.dev.conf"
fi

mkdir -p certs addons ent

if [[ ${#CREATED[@]} -gt 0 ]]; then
  cat > "$SECRETS_FILE" <<EOF
# Generated $(date -u +"%Y-%m-%d %H:%M:%S UTC") by scripts/setup.sh
# Copy to your password manager, then:  rm .setup-secrets
# NEVER commit this file.

${SECRETS_BODY}Database name (must match dbfilter in odoo.conf):
  ODOO_DB_NAME=${ODOO_DB_NAME}

Files created: ${CREATED[*]}
EOF
  chmod 600 "$SECRETS_FILE"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  Passwords saved to: .setup-secrets"
  echo "  Copy to your password manager, then:  rm .setup-secrets"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
else
  echo "All config files already exist — passwords unchanged."
  echo "To regenerate on a fresh machine only: remove the files and run make setup again."
fi

echo ""
echo "Production:  make prod   (or ./prod)"
echo "Local dev:   make dev    (or ./dev)"
echo ""
echo "Backups (on VPS):  make backup   — see docs/BACKUPS.md"
echo "Still edit: apache/vhosts/odoo.conf, certs/, addons/"
